### ISSUE TITLE
Use standard constants where possible

### ISSUE THREAD

**Issue by podhrmic** [rems-project/cn-tutorial#25]
In the tutorial, in any example past the first one, we should be using `MINi32()` and `MAXi32` instead of 2147483647i64

Note:
* I recommend following the C convention, so rename `MINi32()` to `INT32_MAX()`
* [add_5.c](https://github.com/rems-project/cn-tutorial/blob/main/src/example-archive/simple-examples/working/add_5.c) is a good example

**Comment by septract** [comment]
Looks like this is done
