### ISSUE TITLE
Tutorial links to examples are broken

### ISSUE THREAD

**Issue by septract** [rems-project/cn-tutorial#31]
**replication:**
1. Open tutorial on GitHub pages [here](https://rems-project.github.io/cn-tutorial/)
2. Click on the first example link, [solutions/0.c](https://rems-project.github.io/cn-tutorial/solutions/0.c)
3. result: 404

This worked as of last week, but now it seems to be broken

**Comment by bcpierce00** [comment]
Hum -- not sure what's happening here, I'm afraid.  The tutorial looks fine
when I build it locally, and I don't really understand how the deployment
to github pages works.  Happy to try to look at it together with someone
who does...
