### ISSUE TITLE
Turn on branch protection

### ISSUE THREAD

**Issue by septract** [rems-project/cn-tutorial#41]
We should avoid pushing to `main`, but also retain the ability to do it if strictly necessary. GitHub offers a few tools to control this - see [here](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches). 

I would propose we set this up as follows: 
* Forbid pushing to main, and require all commits to go through PR review 
* Allow admins to circumvent this restriction, with the understanding they will only do so in unusual circumstances.

**Comment by bcpierce00** [comment]
I agree this is a reasonable step, with so many people working on the repo
now.

We should also find a way to discuss / implement a bit of directory
structure rationalization.

**Comment by septract** [comment]
Separate ticket to discuss rationalizing the directory structure: #43

**Comment by dc-mak** [comment]
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches#require-linear-history

Perhaps this (and its pre-reqs) as a minimum to start?

**Comment by septract** [comment]
Are there counter arguments to just turning on branch protection fully? If we can reach consensus, I'd rather do the right thing first time

**Comment by septract** [comment]
Fully means my original proposal, as opposed to @dc-mak's suggestion (which I took to be a half-way, but maybe that's an incorrect interpretation?)

**Comment by dc-mak** [comment]
I'm happy with fully, I propose halfway out of pre-emptive pragmatism rather than preference.

**Comment by ZippeyKeys12** [comment]
Are the two not independent? We'd like to require PRs, but we'd also like those PRs to be either squashed or rebased?

**Comment by septract** [comment]
Requiring linear history and forbidding pushes direct to `main` are both good and we should do them both. And no-one seems to have raised any objections to this idea. 

@cp526 or someone else with privileges, can you turn this on?

**Comment by cp526** [comment]
@septract If I got it right, this should be in place now: main has to have linear history, and commits to main have to go via pull requests from branches.

**Comment by septract** [comment]
Yes, looks like this is working. Thanks!
