### ISSUE TITLE
CN Tutorial sections + links

### ISSUE THREAD

**Issue by lwli11** [rems-project/cn-tutorial#61]
Is there a way to add a table of contents at the start so the tutorial is navigable, like: "Add link to a section in Markdown" https://itsfoss.com/markdown-links/ 

It's unnecessarily time-consuming to find individual sections.

**Comment by bcpierce00** [comment]
I don't think it is with the current tool we're using to typeset the
tutorial.  But changing to a different tool is on our list, at some point.
We do recognize it's getting a bit out of hand.

**Comment by cp526** [comment]
Turns out you can – this should now be in place.

**Comment by cp526** [comment]
(But we may still want to change the tool at some point, of course.)
